name = "boslaantje-status"
main = "src/index.js"
compatibility_date = "2026-07-18"

[[kv_namespaces]]
binding = "STATUS_KV"
id = "59ec8744aac44818b0fcb09a0724b5fb"

[triggers]
crons = ["*/5 * * * *"]

[vars]
TRIGGER_KEY = "dd3f5385bedf960a7da62448fe983348"
MAKE_WEBHOOK_URL = "https://hook.eu1.make.com/fubsfyk0lc76kt72ncfpfetckfkyr27s"
